### ISSUE TITLE
Fails if packages directory issue

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge-dev-env#24]
### Current Behavior

If `packages/` does not exist then init fails

### Expected Behavior

Init should work

### Steps To Reproduce

Delete packages directory, run npm init

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
just been caught with this. I have a fix in place - happy to PR
