### ISSUE TITLE
Error running npm run init

### ISSUE THREAD

**Issue by ilpise** [flowforge/flowforge-dev-env#5]
When running the `init.js` script the repositories are cloned using 
```
git clone git@github.com:flowforge/${options.packages[i]}.git
```
which give this error
```
Failed to clone flowforge/flowforge: Error: Command failed: git clone git@github.com:flowforge/flowforge.git
Cloning into 'flowforge'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
use the https clone
`git clone https://github.com/flowforge/${options.packages[i]}.git`

works correctly

**Comment by knolleary** [comment]
Hi @ilpise - great point. I'd created this with our core team in mind who do have authenticated access to the repos. But it was also meant for anyone else to use - so we should add a way to pick https/git clones.
